### ISSUE TITLE
Switch between command lines emulators

### ISSUE THREAD

**Issue by Purgator** [CK-Build/CKli#13]
Hello,

In case of the "run \*command\*" command...
Could you add the possibility to gives a path to an other shell than cmd or powershell  please ?
It could be really useful.

Example. I work on a world that have a lot of .sln in different directories. I want to open them all in visual studio. I can't right now cause classic windows shells does not support wildcard. sh provided by git can handle it without any difficulty.

In most case, it provides a bunchload of feature without any more extra development. Amazing ?

Thanks.

**Comment by Kuinox** [comment]
I don't think it's caused by bash/powershell.   
Are you sure it's not devenv that doesnt understand the globbing pattern ?
AFAIK you can run bash from powershell

**Comment by bcrosnier** [comment]
Bash does [filename expansion](https://www.gnu.org/software/bash/manual/html_node/Filename-Expansion.html), typically done by the shell. Neither `cmd` nor Powershell does this by default.

`devenv` does not expand any wildcard in the command, and more importantly, does not support multiple solutions at the same time - calling `devenv A.sln B.sln` will not work, so filename expansion is not going to work anyway. `devenv` must be invoked one per solution.

Here's your Powershell one-liner to open all *.sln in the current directory :

`gci -Recurse -Filter *.sln | %{ $_.FullName } | %{ &"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\devenv.exe" $_ }`

**Comment by Kuinox** [comment]
I changed the RunCommand, it's now RunProcess and allow you to specify the binary to launch.
Should solve this issue.
It also solve cross compatibility.
It's a simple wrapper arround ProcessRunner.Run.

**Comment by Purgator** [comment]
Amazing ! That exactly what I want thank you.
I have to test it now ;)

@bcrosnier I assume there is only 1 .sln in a directory.
