### ISSUE TITLE
Create more env variables

### ISSUE THREAD

**Issue by Purgator** [CK-Build/CKli#14]
Hello,

Could you add some environment variables that are bind when we enter into a world.

As,

Current solution name
Current solution file name

Thank you

**Comment by olivier-spinelli** [comment]
Something like CKLI_CURRENT_WORLDNAME? This is easy. However the notion of "current solution" is a little bit more tricky.
During a AllBuild or a Release (or any transversal "execution") the CKLI_CURRENT_SOLUTION_NAME may be updated... but... may be an easier (and more versatile) solution would be to "Officially" state that whenever CKLI interacts with ONE solution then the current directory is set to the solution folder...
Ideas?

**Comment by Kuinox** [comment]
After reading #13, I think he meant that we add env variables when we run the user command so he can run `devenv %SolutionName%.sln` to launch Visual Studio on every sln.

**Comment by olivier-spinelli** [comment]
ok :)
And what about the "set current directory" option (the name is the name of the current directory... by design)?

**Comment by Kuinox** [comment]
It's already enabled :D.
Adding env variable would allow to do easy one liner where a more complex logic would be required o retrieve the sln name.

**Comment by Purgator** [comment]
The current directory is not perfect because (if I understand well) it would result as doing this cmd :
`devenv.exe .`
On every directory. It's impossible to build the solution inside visual studio after that.

I started thinking about this because after running `World/ShowExternalDependencies`, it output all *.sln dependencies and versions.
I updated a lot of dependencies then.
What I want right now is opening visual studio on every solution (or at least modified solutions) to handle potentials breaking changes or such. I did it without CKli but I think that could help for the future.
It is for my use case related to #13 but still can be useful in some other use cases (maybe).

**Comment by Kuinox** [comment]
@Purgator without it you can parse your current path, extract the last part, then do LastPart.sln (it work if it respect our standard).
Issues are:
* when solution does not respect the standard it won't work
* It's a pain to write.

**Comment by Kuinox** [comment]
@olivier-spinelli Tought this issue would be easy but it's not.   
The command `RunCommand` is located in the GitFolder, you dont need a Solution to use it.
We need something where the object using the GitFolder can add environement variables for the commands.  
A simple List could do it ?

**Comment by olivier-spinelli** [comment]
I've added an event on the GitFolder, the SolutionDriver subscribes and, before any RunProcess, adds these environment variables:

```csharp
        void OnRunProcessStarting( object sender, RunCommandEventArgs e )
        {
            e.StartInfo.EnvironmentVariables.Add( "CKLI_CURRENT_WORLD_FULLNAME", GitFolder.World.FullName );
            e.StartInfo.EnvironmentVariables.Add( "CKLI_CURRENT_WORLD_NAME", GitFolder.World.Name );
            ISolution s = GetSolution( e.Monitor, true );
            if( s != null )
            {
                e.StartInfo.EnvironmentVariables.Add( "CKLI_CURRENT_SOLUTION_NAME", s.FullPath.LastPart );
            }
        }
```
Are these enough?

**Comment by Purgator** [comment]
Yes please !
