### ISSUE TITLE
UpgradeDependency wrong parsing ?

### ISSUE THREAD

**Issue by Purgator** [CK-Build/CKli#18]
Hello,

I encountered an edge case while upgrading an external dependency I think.

Expected :
`
    <PackageReference Include="NetTopologySuite.IO.GeoJSON" Version="1.15.6-rc.1" />
`
Reality :
`
    <PackageReference Include="NetTopologySuite.IO.GeoJSON" Version="1.15.6-r01" />
`

**Comment by olivier-spinelli** [comment]
:D They use the long form of CSemVer... No luck, the current implementation normalizes it to the short form and that's a bug!
