### ISSUE TITLE
Possibility to set a default password for the personal keyvault

### ISSUE THREAD

**Issue by Woinkk** [CK-Build/CKli#37]
When we start CKli for the first time it will ask the user if he want to set a password, if not then we set a default password

**Comment by olivier-spinelli** [comment]
The idea is to still crypt the secrets in the keyvault.txt file, even if no password is asked any more.

**Comment by Kuinox** [comment]
If the password is the same globally then we should at least use a strong password (the user will never see this password anyway)

We can also make the default password use an HWID which would be better if a KeyVault is leaked by accident.
